### ISSUE TITLE
unicode chars doesn't work

### ISSUE THREAD

**Issue by eoli3n** [osa1/tiny#193] opened 2020-05-10 20:13 UTC
At the bottom you can see that the same chars are working in my terminal.
![img](https://x0.at/0Bq.png)

**Comment by osa1** [comment] 2020-05-10 23:10
Thanks for reporting.

I think this is an encoding issue. The original IRC protocols (RFC 1459 and 2812) are ASCII-based so encoding of unicode characters is not specified. I may be wrong, but I suspect current servers do not care about encoding of user messages, for example if a user sends unicode characters encoded in, say, UTF-16, servers are happy to send those to receivers in the same encoding (is there even a way for servers to figure out encoding of messages, in general?), but because there isn't a standard encoding specified, a client that expects messages to be encoded in UTF-8 (e.g. tiny) will decode it incorrectly. I think this is precisely what's happening here (except the sender's encoding may not be UTF-16 but something else).

It'd be good to know:

1. The encoding used by the sender in this screenshot
2. How other widely used IRC clients decode incoming messages

**Comment by eoli3n** [comment] 2020-05-11 07:22
> The encoding used by the sender in this screenshot

How to give you that ?

> How other widely used IRC clients decode incoming messages

I don't have that problem with weechat.

**Comment by FreeFull** [comment] 2020-05-11 07:59
irssi makes an effort to detect what encoding was used, and re-encode the message. Weechat probably does too. That sort of approach is based on heuristics so is imperfect, and I'm not sure how complicated it might be to implement.

**Comment by osa1** [comment] 2020-05-11 10:44
@eoli3n how are you testing this in weechat and irssi? I'd like to use a similar setup to test tiny.

**Comment by eoli3n** [comment] 2020-05-11 11:28
Actually... on 2 hosts, without changing anything, it seems to work now... there's something i don't get here.

**Comment by osa1** [comment] 2020-05-18 01:11
I briefly looked at hexchat and irssi for how they decode incoming messages.

- [Relevant code in irssi][1]: from a quick look it seems like users can specify an encoding and UTF-8 is the default. There's also a "fallback" option which is CP1252. Not sure what happens if the incoming message is not encoded in any of these.

- [Relevant code in hexchat][2]: User can specify an encoding (in server settings), UTF-8 is the default. Invalid sequences are replaced with "The Unicode replacement character" (0xFFFD).

Implementing (2) is trivial as we already have [the function in std][3]. I think we should just do that.

[1]: https://github.com/irssi/irssi/blob/master/src/core/recode.c
[2]: https://github.com/hexchat/hexchat/blob/master/src/common/text.c
[3]: https://doc.rust-lang.org/nightly/std/string/struct.String.html#method.from_utf8_lossy

**Comment by osa1** [comment] 2020-05-18 10:38
I'm closing this as we don't have a reproducer, and @eoli3n mentioned above that they can't reproduce this. 

UTF-8-encoded characters always worked fine, for non-UTF-8 encodings, we previously did some unsafe stuff which I just fixed, in the worst case you should now see `�` characters.

Note that we also assume that the terminal encoding is UTF-8 so if your terminal is not configured for that, changing that may fix the original problem you reported.

@eoli3n please re-open if you have this problem again.

**Closed by osa1** 2020-05-18 10:38 UTC
Labels: bug, question
