### ISSUE TITLE
Showing logged data on next run?

### ISSUE THREAD

**Issue by salkin-mada** [osa1/tiny#268] opened 2020-11-17 08:46 UTC
Hi,
Isn't `tiny` supposed to "load" the logged data of channels the next time it opens?
I have some nice logged chats here.
```
.rw-r--r--   57k salkin 17 Nov  9:33  chat.freenode.net.txt
.rw-r--r--   68k salkin 17 Nov  9:33  chat.freenode.net_##rust.txt
.rw-r--r--   13k salkin 17 Nov  9:33  chat.freenode.net_#archlinux-arm.txt
.rw-r--r--  139k salkin 17 Nov  9:33  chat.freenode.net_#archlinux-offtopic.txt
.rw-r--r--  163k salkin 17 Nov  9:33  chat.freenode.net_#archlinux.txt
.rw-r--r--   608 salkin 17 Nov  9:33  chat.freenode.net_#cargo.txt
.rw-r--r--  7,2k salkin 17 Nov  9:33  chat.freenode.net_#rust-beginners.txt
.rw-r--r--  7,5k salkin 17 Nov  9:33  chat.freenode.net_#supercollider.txt
.rw-r--r--   38k salkin 17 Nov  9:33  chat.freenode.net_#sway.txt
.rw-r--r--  7,6k salkin 15 Nov 17:13  chat.freenode.net_alis.txt
.rw-r--r--   155 salkin 15 Nov 12:09  FREENODE.txt
.rw-r--r--   45k salkin 17 Nov  9:33  irc.oftc.net.txt
.rw-r--r--  6,4k salkin 17 Nov  9:33  irc.oftc.net_#tiny.txt
.rw-r--r--  2,7k salkin 17 Nov  9:33  mentions.txt
```
put when i rerun `tiny` this is the result:
![scrn-2020-11-17-09-45-58](https://user-images.githubusercontent.com/12082586/99366991-a8bdbd80-28b9-11eb-9d46-2eed46e44940.png)

**Comment by osa1** [comment] 2020-11-17 08:50
It isn't supposed to do this, but I agree it would be good to do this. I had this mind for a while but never got around designing and implementing it. The logs are there for you to refer to them later if you need it :-) You can disable logging if you want by removing the `log_dir` line in your config.

I'm turning this into a "feature request".

**Comment by osa1** [comment] 2020-12-09 13:44
Closing this as duplicate of #57.

**Closed by osa1** 2020-12-09 13:44 UTC
Labels: feature request
