### ISSUE TITLE
Tiny joins channels before nick is identified with the server

### ISSUE THREAD

**Issue by reading123** [osa1/tiny#67] opened 2017-12-24 04:38 UTC
In the auto_cmds: section of the config I have two commands: 
msg nickserv identify (password)
and 
join ##linux,#archlinux,#archlinux-offtopic,#(etc)

Tiny executes the second command before the server has responded and identified me. Many channels won't let you join unless you're identified with NickServ, or forward you to a different channel (##linux-overflow,#archlinux-unregistered). 
How can I make Tiny wait between sending the first command and the second command?

**Comment by osa1** [comment] 2017-12-24 07:16
Actually tiny runs all auto_cmds other than joins first (on reply 001), and runs joins later (on reply 376), but these commands are handled asynchronously by the server (and `NickServ` etc.) so they're handled out of order.

Closing this as I think it is a duplicate of #30 . Please re-open if this is different than #30.

**Closed by osa1** 2017-12-24 07:16 UTC
