### ISSUE TITLE
Mentions or direct messages cause tiny to exit without warning

### ISSUE THREAD

**Issue by wrycode** [osa1/tiny#97] opened 2018-04-10 03:16 UTC
I installed Tiny on top of a freshly created Debian 9 server. Rust was installed via the official Rustup script, and then updated to nightly. In order to compile Tiny, I needed to install the following packages with apt:
`git gcc make libssl-dev libdbus-1-dev`
or the cargo command would throw me various errors.
Here's the only odd-looking output from my shell after [this rust issue](https://github.com/rust-lang/rust/issues/49635) was resolved:
```
   Compiling serde_yaml v0.7.3              
warning: redundant linker flag specified for library `dbus-1`
                                          
   Compiling syn v0.13.1                         
   Compiling backtrace v0.3.5                                       
   Compiling serde_derive_internals v0.23.0                                          
   Compiling error-chain v0.10.0   
   Compiling native-tls v0.1.5                                                                        
   Compiling term_input v0.1.3        
   Compiling serde_derive v1.0.37                                                                     
   Compiling notify-rust v3.4.2    
   Compiling tiny v0.4.1 (file:///home/wrycode/build/tiny)
warning: this feature has been stable since 1.26.0. Attribute no longer needed
 --> src/lib.rs:9:12               
  |                             
9 | #![feature(inclusive_range_syntax)]
  |            ^^^^^^^^^^^^^^^^^^^^^^
  |                                  
  = note: #[warn(stable_features)] on by default
                                      
    Finished release [optimized] target(s) in 375.41 secs
  Installing /home/wrycode/.cargo/bin/tiny                
```
Now, only with this installation of Tiny, any direct message or mention in a channel causes Tiny to crash without warning. From Irssi, this message is displayed when this happens:
`21:32 -!- wrycode [mem.espitti@moz-r3b.7do.32.45.IP] has quit [A TLS packet with unexpected length was received.]`

**Comment by osa1** [comment] 2018-04-10 05:14
Thanks for reporting. I can't reproduce this. For example, your mentions to me few hours ago on #tiny did not cause my tiny to crash. Could you try again with `RUST_BACKTRACE=1 tiny 2>err` (if possible, using debug build) and let me know the contents of `err` file after tiny crashes?

**Comment by wrycode** [comment] 2018-04-11 01:34
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error(Dbus(D-Bus error: Unable to autolaunch a dbus-daemon wit
hout a $DISPLAY for X11 (org.freedesktop.DBus.Error.NotSupported)), State { next_error: None, backtrace: Some(stack backtrace:
   0:     0x55f1fc32d404 - backtrace::backtrace::libunwind::trace::h8af24942909c73e6
                        at /home/wrycode/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.5/src/backtrace/libunwind.rs:53
                         - backtrace::backtrace::trace::h4641e9e25746f83d
                        at /home/wrycode/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.5/src/backtrace/mod.rs:42
   1:     0x55f1fc327d3c - backtrace::capture::Backtrace::new_unresolved::h04940d53c87066fb
                        at /home/wrycode/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.5/src/capture.rs:88
   2:     0x55f1fc327c8e - backtrace::capture::Backtrace::new::hbd9b2693f81fb436
                        at /home/wrycode/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.5/src/capture.rs:63
   3:     0x55f1fc3269e2 - error_chain::make_backtrace::h3af37b517d19de13
                        at /home/wrycode/.cargo/registry/src/github.com-1ecc6299db9ec823/error-chain-0.10.0/src/lib.rs:417
   4:     0x55f1fc326a7f - <error_chain::State as core::default::Default>::default::h93910c5478e4ef34
                        at /home/wrycode/.cargo/registry/src/github.com-1ecc6299db9ec823/error-chain-0.10.0/src/lib.rs:504
   5:     0x55f1fc31bcf5 - notify_rust::error::Error::from_kind::h35368945c08bcc5e
                        at /home/wrycode/.cargo/registry/src/github.com-1ecc6299db9ec823/notify-rust-3.4.2/<error_chain_processed macr
os>:52                 
   6:     0x55f1fc31bdbd - <notify_rust::error::Error as core::convert::From<dbus::Error>>::from::h01cd11ed6c8a5b28
                        at /home/wrycode/.cargo/registry/src/github.com-1ecc6299db9ec823/notify-rust-3.4.2/<error_chain_processed macr
os>:85                                 
   7:     0x55f1fc316403 - notify_rust::Notification::show::h5ddc7d85198d6fa4
                        at /home/wrycode/.cargo/registry/src/github.com-1ecc6299db9ec823/notify-rust-3.4.2/src/lib.rs:496
   8:     0x55f1fc2ffab9 - tiny::notifier::notify::he171e9b1e08fdfad
                        at src/notifier.rs:13      
   9:     0x55f1fc2fff0b - tiny::notifier::Notifier::notify_privmsg::he0cfb07e099d0df8
                        at src/notifier.rs:35
  10:     0x55f1fc2c013f - tiny::tui::TUI::add_privmsg_highlight::{{closure}}::h2c467ff9d2dd8b02
                        at src/tui/mod.rs:992
  11:     0x55f1fc2b8068 - tiny::tui::TUI::apply_to_target::h5776becdaa990566
                        at src/tui/mod.rs:901
  12:     0x55f1fc2222c2 - tiny::tui::TUI::add_privmsg_highlight::he734de8b5e417155
                        at src/tui/mod.rs:988
  13:     0x55f1fc217c32 - tiny::Tiny::handle_msg::hdedc151b4852ed9a
                        at src/lib.rs:554
  14:     0x55f1fc2169a0 - tiny::Tiny::handle_conn_ev::h5da9eb0ae09c532d
                        at src/lib.rs:507
  15:     0x55f1fc215bd1 - tiny::Tiny::handle_conn_evs::h695788e2b017ba5e
                        at src/lib.rs:420
  16:     0x55f1fc2158fd - tiny::Tiny::handle_socket::h7ac4ff4254ca6377
                        at src/lib.rs:415
  17:     0x55f1fc2133b6 - tiny::Tiny::run::h3528982efd3aac4e
                        at src/lib.rs:217
  18:     0x55f1fc2122df - tiny::run::h133d1cc3b2b5fae1
                        at src/lib.rs:110
  19:     0x55f1fc211a38 - tiny::main::h005b6043b3199cf2
                        at bin/main.rs:4
  20:     0x55f1fc211ae1 - std::rt::lang_start::{{closure}}::hbf788cb9c0aa3b46
                        at /checkout/src/libstd/rt.rs:74
  21:     0x55f1fc3f8797 - std::rt::lang_start_internal::{{closure}}::ha4e6f269ebba9c4a
                        at libstd/rt.rs:59   
                         - std::panicking::try::do_call::hdec9e3cbcdfae56c
                        at libstd/panicking.rs:305
  22:     0x55f1fc40957e - __rust_maybe_catch_panic
                        at libpanic_unwind/lib.rs:102
  23:     0x55f1fc3efc85 - std::panicking::try::hc9c379749bb58872
                        at libstd/panicking.rs:284
                         - std::panic::catch_unwind::h18a3fa96a8d08a28
                        at libstd/panic.rs:361
                         - std::rt::lang_start_internal::h52bfa0963a3ec8bf
                        at libstd/rt.rs:58
  24:     0x55f1fc211ac1 - std::rt::lang_start::h4c48cb8d1e7fd8a7
                        at /checkout/src/libstd/rt.rs:74
  25:     0x55f1fc211a6d - main
  26:     0x7fe0008292e0 - __libc_start_main
  27:     0x55f1fc2118d9 - _start
  28:                0x0 - <unknown>) })', libcore/result.rs:945:5                                                            
stack backtrace:                                                                    
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace                                                                       
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49            
   1: std::sys_common::backtrace::print                                                                                         
             at libstd/sys_common/backtrace.rs:71                                          
             at libstd/sys_common/backtrace.rs:59                                                                         
   2: std::panicking::default_hook::{{closure}}                                 
             at libstd/panicking.rs:206                                                                                   
   3: std::panicking::default_hook                                       
             at libstd/panicking.rs:222                                                                                   
   4: std::panicking::rust_panic_with_hook                                                           
             at libstd/panicking.rs:400                                                                                   
   5: std::panicking::begin_panic_fmt                                             
             at libstd/panicking.rs:347                                                                                               
   6: rust_begin_unwind
             at libstd/panicking.rs:323                                                                            
   7: core::panicking::panic_fmt                                                                                                      
             at libcore/panicking.rs:71
   8: core::result::unwrap_failed                                            
             at /checkout/src/libcore/macros.rs:26                                                                       
   9: <core::result::Result<T, E>>::unwrap                          
             at /checkout/src/libcore/result.rs:782
  10: tiny::notifier::notify                                                          
             at src/notifier.rs:13           
  11: tiny::notifier::Notifier::notify_privmsg                                                  
             at src/notifier.rs:35           
  12: tiny::tui::TUI::add_privmsg_highlight::{{closure}}                     
             at src/tui/mod.rs:992           
  13: tiny::tui::TUI::apply_to_target                                              
             at src/tui/mod.rs:901           
  14: tiny::tui::TUI::add_privmsg_highlight                         
             at src/tui/mod.rs:988       
  15: tiny::Tiny::handle_msg                                            
             at src/lib.rs:554           
  16: tiny::Tiny::handle_conn_ev                                         
             at src/lib.rs:507           
  17: tiny::Tiny::handle_conn_evs                                      
             at src/lib.rs:420           
  18: tiny::Tiny::handle_socket                              
             at src/lib.rs:415           
  19: tiny::Tiny::run                                  
             at src/lib.rs:217           
  20: tiny::run                                         
             at src/lib.rs:110          
  21: tiny::main                                                              
             at bin/main.rs:4                           
  22: std::rt::lang_start::{{closure}}                                                 
             at /checkout/src/libstd/rt.rs:74
  23: std::panicking::try::do_call                                        
             at libstd/rt.rs:59                   
             at libstd/panicking.rs:305            
  24: __rust_maybe_catch_panic                       
             at libpanic_unwind/lib.rs:102                       
  25: std::rt::lang_start_internal                
             at libstd/panicking.rs:284                               
             at libstd/panic.rs:361           
             at libstd/rt.rs:58                                           
  26: std::rt::lang_start                 
             at /checkout/src/libstd/rt.rs:74                    
  27: main                                              
  28: __libc_start_main        
  29: _start                       
```

**Comment by wrycode** [comment] 2018-04-16 20:03
With that patch applied, I get this text that covers the chat screen:

```
Error when showing notification: Error(Dbus(D-Bus error: Unable to autolaunch a dbus-daemon without a $DISPLAY for X11 (org.freedesktop.DBus.Error.NotSupported)), State { next_error: None, backtrace: None })
```
But Tiny doesn't crash, and I can type messages that clear out the error

**Comment by osa1** [comment] 2018-04-17 17:48
Right, so this seems like a problem with your dbus configuration. A quick google search for "unable to autolaunch a dbus-daemon" yields some commands that update some env variables etc. Could you try some of those?

**Comment by osa1** [comment] 2018-07-30 07:31
The problem on tiny's part is fixed so closing this.

**Closed by osa1** 2018-07-30 07:31 UTC
Labels: bug
